apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: configmap-leys-mutating-configuration
webhooks:
  - name: pod-policy.example.com
    rules:
      - apiGroups:   []
        apiVersions: [v1]
        operations:  [CREATE, UPDATE]
        resources:   [configmaps]
        scope:       Namespaced
    clientConfig:
      service:
        name: example-service
      caBundle: <CA_BUNDLE>
    admissionReviewVersions: [v1]
    sideEffects: None
    timeoutSeconds: 5