name: Build and Push Image

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_REPOSITORY: nivesh00
  DOCKER_IMAGE_NAME: configmap-manager
  DOCKER_IMAGE_TAG: "v1.0.0"

on:
  push:
    # Only run on `main`
    branches:
      - main

jobs:
  docker_image:
  
    runs-on: ubuntu-latest

    environment: configmap-manager

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Do not get extra git branches to save time

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and Push the Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}
            ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ACCESS_TOKEN }}
